### ISSUE TITLE
Add unsubscribe button to each email

### ISSUE THREAD

**Issue by nabilbaugher** [jackbisceglia/internship-tracker#39]
<a> tag with url that goes to the frontend with user id to be consumed by the frontend

**Comment by joepetrillo** [comment]
I made an unsubscribe page today where users can enter their email and the server would handle deleting them from the DB. Maybe we can have the link just go to that page?

**Comment by jackbisceglia** [comment]
@joepetrillo Current idea is to have a button in every email to redirect users to:
 `domain/unsubscribe/<some combination of userId and sign up date>`

So yea, this works. Need to hop on call or something and discuss more detailed Delete functionality though
