### ISSUE TITLE
Protect Listing Page

### ISSUE THREAD

**Issue by jackbisceglia** [jackbisceglia/internship-tracker#76]
Need a clean way to protect Listings page while still in development. 

Now that the email list is _pretty much_ complete, we want to roll out MVP. Need to protect this in prod. Some ideas:
- check if environment variable "PROD" exists -> if so, render a "coming soon" message or something. if not, render table for development purposes
- Just comment out old code in prod and render a "coming soon" message

Tagging you in friend @joepetrillo. It's actually a pretty quick fix. I'm just gonna be stucking doing deployment stuff. If you don't get around to it I can handle it.

not really sure which is better lol

:shipit:

**Comment by joepetrillo** [comment]
Yeah I can figure this out
